server:
  port: ${SERVER_PORT:8080}


spring:
  webflux:
    multipart:
      max-in-memory-size: 4MB
      max-parts: 32
      max-disk-usage-per-part: -1
      max-headers-size: 5KB


r2dbc:
  hostname: ${R2DBC_HOSTNAME:localhost}
  port: ${R2DBC_PORT:45432}
  username: ${R2DBC_USERNAME:dev-user}
  password: ${R2DBC_PASSWORD:password}
  database: ${R2DBC_DATABASE:gallerworx_dev}
  schema: ${R2DBC_SCHEME:public}
  timezone: ${R2DBC_TIMEZONE:UTC}
  auto-detect-extensions: ${R2DBC_AUTO_DETECT_EXTENSIONS:true}
  tcp-no-delay: ${R2DBC_TCP_NO_DELAY:true}
  tcp-keep-alive: ${R2DBC_TCP_KEEP_ALIVE:true}
  pool:
    enabled: true
    initial-size: 4
    max-size: 16
    max-idle-time: 15m